### PR TITLE
Toolbar

### PR DESCRIPTION
**Pull request by niklasberglund**
Replacing PR #754 with this PR for the _toolbar_ branch of the macdown repo so it's easier for others to make changes to it.

Added toolbar support. Show the toolbar by going to _View_ => _Show toolbar_ or hit the keyboard shortcut ⌘⌥T.

Simplified the toggling editor/preview options(rightmost button in the default set) as discussed on Gitter. Also there's no icon for that button. I borrowed the "hide preview" icon.

### CODE REVIEW

**Comment by niklasberglund** [comment]
In it's current state the toolbar with the default set look like this:
image

**Comment by uranusjr** [comment]
Yay! This looks awesome. Unfortunately I’m trying to finish my slides for [PyCon APAC](https://pycon.my) (26–27) atm, and won’t have time to take a look until the end of the month. I promise I will come back to this after the conference. 😞 Do ping me for any questions though! Really want this in the next release.

**Comment by niklasberglund** [comment]
Ah nice, enjoy! Just wondering about the "layout" button(rightmost one).

image


1. Do the options make sense?
2. Should we see if we can have an icon made for it?
3. Should this button work in a similar way with the touch bar?

Tempted to help @brunophilipe out with the touch bar branch if he don't mind. I've got a new Macbook pro with touch bar now. Would be cool if next release have both toolbar and touch bar support.

@uranusjr I got a feeling you haven't checked Gitter in a while 😊 Left you a few messages there.

**Comment by uranusjr** [comment]
The options make sense for me, but I’m open for opinions. Does it feel Mac-native to have icons in the dropdown?

**Comment by MyTheValentinus** [comment]
Hello, when the toolbar was release ? Thanks

**Comment by niklasberglund** [comment]
> Hello, when the toolbar was release ? Thanks

@MyTheValentinus I think the plan is to include the toolbar in next MacDown release.


> Does it feel Mac-native to have icons in the dropdown?

@uranusjr maybe it'd be a nice detail. We could try and see what it looks like. Seems like Apple seldom use menu item icons in their own applications but wouldn't hurt.

**Comment by niklasberglund** [comment]
Will update this PR to only show formatting plugins' buttons when they have been enabled. Like what @brunophilipe did for the touch bar:

screen shot 2017-08-28 at 21 10 25

**Pull request merged**
