### PR TITLE
Toolbar improvements

### PR DESCRIPTION
**Pull request by alexkaessner**
As discussed in issue #282, I've made some minor improvements to the toolbar. It mainly includes visual changes, as well as improved labels, a better default toolbar and 🇩🇪 localization for the labels.

### CODE REVIEW

**Comment by franklinyu** [comment]
1. So we go for the "no icon" solution instead of the "flip image", right?
 2. Do we add the translation here? I don't think it would synchronize back to Transifex…

**Comment by alexkaessner** [comment]
1. @niklasberglund removed the 3-button-switch for the layout option. I personally prefer the 3-button-segmented control over the dropdown menu, but my coding skills are too bad to make it right. 😅 Cause if we wanna do it, we have to show the user what the current state is to make it clear.
2. Oh okay. Didn't know how the translation is made. How can I fix this?

**Comment by alexkaessner** [comment]
@franklinyu What do I have to do, to make it worth merging this pull request? Should I remove the translation again (and put it in the translation service)?

**Comment by alexkaessner** [comment]
@franklinyu @uranusjr I've now removed the localization from the `Localizable.strings` files, so that it should work with Transifex.
I've changed some menu entries and removed unused toolbar buttons in the xib file before. Don't know how to handle the conflict here. **Are you handling the merge? Or what should I do to make it merge ready?**

PS: Let's finish this polish on the toolbar and make it ready to ship! 😉

**Comment by franklinyu** [comment]
Yes I can handle the conflict! It's due to Xcode frequently change some strange version number.<sup>1</sup>

Sorry I'm not good at reviewing actual code, so this would take longer than before (used to be @uranusjr, but he doesn't seem to be available recently).

<sub>1. Because Apple thinks that it's internal API, the team changes it *all the time*! Same issue with Storyboard! Fix is simple, just pick the larger number 🙄 .</sub>

**Comment by uranusjr** [comment]
Just made a change to the toolbar code in afcc017768, so might to want to watch out when rebasing… I’ll do the merge after that!

**Comment by uranusjr** [comment]
OMG GitHub’s online conflict resolution tool is so awesome.

**Comment by uranusjr** [comment]
The tests need an upgrade on Travis to pass. Merged manually.

**Pull request merged**
