### PR TITLE
Toolbar

### PR DESCRIPTION
**Pull request by niklasberglund**
This code isn't ready yet. Creating the PR in case you have any feedback on the work in progress. The code got quite verbose. Started writing the toolbar code in `MPDocument` but broke it out into it's own class `MPToolbarController` which is the `NSToolbar` delegate.

Toolbar items and their actions are configured in the `setupToolbarItems` method. Wanted to have all items configured in one place. 

It's in a usable state. Going to make small change to highlighting, add spacing, fine tune code. The toolbar is very much affected by #753.

### CODE REVIEW

**Comment by uranusjr** [comment]
Wow 99 files changed. Those image assets really stack up very quickly.

**Comment by franklinyu** [comment]
Any rationale for choosing XIB instead of storyboard?

**Comment by uranusjr** [comment]
@franklinyu Storyboard is only available after 10.10, IIRC.

**Comment by franklinyu** [comment]
Oh, another Yosemite thing besides `WKWebView`! Do you think we should update them when we drop Mavericks in future?

**Comment by niklasberglund** [comment]
The code base is already using the xib approach rather than storyboards. There's pros and cons with both approaches and developers have different opinions of which one is better.

Personally I prefer xib files because it can be slow to have a big storyboard open, xib files gives easier to read diffs and less merge conflicts since it's not as likely that several persons made changes in the same file.

**Comment by franklinyu** [comment]
@niklasberglund I have heard that you can actually use storyboard as XIB, that is, one storyboard per component. Segue between storyboards can be created within Interface Builder.

**Comment by niklasberglund** [comment]
@franklinyu cool. But wouldn't that be missing the point of storyboards a bit if separate into many files? I'm not too familiar with storyboards, only used it a bit when it was new. I can imagine that it's improved a lot now.

Is it still true that storyboards vs xib files is just a different way to work with the UI? Or are there things that can be done with storyboards which we can't do with xib files?

**Comment by niklasberglund** [comment]
Merge conflicts in storyboards shouldn't be as big of an issue nowadays I guess. Since Xcode isn't changing as many values in xib/storyboard files now as before, and git has improved as well.

**Comment by uranusjr** [comment]
Storyboards are cool and I use them all the time on iOS, but XIBs are fine for MacDown. Desktop applications usually have only a handful of views visible at a time, and the relation between them is usually pretty separated, unlike on iOS where you usually need to handle a lot of push-pop operations.

In any case, since we already have many working XIBs, there’s no point changing them anyway. The benefit is pretty marginal IMO.

**Comment by niklasberglund** [comment]
This PR should be ready for review now 👌
Try hiding both editor and preview panes and see how you think of the highlighting. Right now neither will be highlighted. But one of them is still visible taking up the entire window.

**Comment by niklasberglund** [comment]
Hmm now I somehow managed to mess upp the highlighting by clicking on the buttons repeatedly.

Also - is this highlight state correct for the show/hide editor and preview buttons?

image

**Comment by niklasberglund** [comment]
I still need to fix a logged warning and change highlight behaviour according to discussion in #282

**Comment by franklinyu** [comment]
The "blue to show, gray to hide" pattern works for Xcode because the three boolean states are independent of each other in Xcode, which is not the case in MacDown. Here I would suggest having three mutually exclusive buttons like in [this Fiddle](http://jsfiddle.net/jworboys/rUbr9/).

**Comment by niklasberglund** [comment]
@franklinyu yea that would make much sense to me as a user. The show/hide panes functionality has been discussed in a few issues and pull requests. Should it work the same in _View_ menu, toolbar and touch bar? In the _View_ menu and touch bar it could also be three states.

**Comment by franklinyu** [comment]
@niklasberglund Yes I think we should also change how View menu and touch bar looks like. I'm not sure how do @alexkaessner like this "three mutually exclusive buttons" idea. (@brunophilipe probably saw your comment in #732.)

**Comment by brunophilipe** [comment]
I did! =) I even came up with another suggestion, but I figured out it wasn't good, in the end. I just think 3 buttons is too much.

I'll try thinking of something else, and if I come up with anything I'll reply here.

**Comment by niklasberglund** [comment]
Replaced this PR with #839 which is for a branch in the _macdown_ repo so it's easier for others to make changes to the PR. Closing this PR.

**Pull request closed without merging**
