### PR TITLE
Added "Insert Current Date" item in Format menu

### PR DESCRIPTION
**Pull request by JetForMe**
This command replaces the current selection with the current time formatted like `2019-04-02 12:54:00 -0700`, using the system locale and the user’s current time zone.

I found myself needing this frequently with front matter to specify a blog post's date.

### CODE REVIEW

**Comment by FranklinYu** [comment]
Sorry, I think this belongs to a plug-in. Plug-in architecture isn’t well documented, but you can see https://github.com/MacDownApp/macdown-gistit for an example.

**Comment by uranusjr** [comment]
I agree, this is almost the quintessential plugin candidate.

**Comment by JetForMe** [comment]
I didn't even realize there was a plugin architecture. I'll try to re-work it. Too bad it doesn't seem to allow for key equivalents and changing behavior with meta keys, does it?

> On Apr 6, 2019, at 00:49 , Tzu-ping Chung <notifications@github.com> wrote:
> 
> I agree, this is almost the quintessential plugin candidate.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
Rick Mann
rmann@latencyzero.com

**Comment by uranusjr** [comment]
I believe key combinations can be configured in the system preferences.

http://osxdaily.com/2017/08/08/create-custom-keyboard-shortcut-mac/

**Comment by JetForMe** [comment]
So, I finally got around to making this a plug-in. I had to expose access to the editor to get the current selection, but it works. Might be nice to be able to package multiple commands into one plug-in.

**Pull request closed without merging**
