### PR TITLE
[TESTING NEEDED] Reload file by hooking into presentedItemDidChange

### PR DESCRIPTION
**Pull request by uranusjr**
I implemented a file-reloading hook based on feedbacks in #564. I found that `NSDocument` actually already implements Dispatch Sources with `NSFilePresenter` protocol, so I took advantage of this.

Event with this callback, there are still some hoops to jump through. Reverting a document _actually triggers the callback again_, so to prevent the file being reloaded by itself I put a check to make sure the file has been last modified by someone else, not MacDown itself.

Also I decided to only trigger reversion when the file has not been modified by the user. This seems reasonable to me, but I need more feedback from users (yes I’m looking at you reading this) so that I can decide whether it is OK.

You can find a test build at http://macdown.uranusjr.com/history/testing/#version_766.1 that includes changes from #564, this PR, and some other changes. Please test it and tell me what you think. **Use it with caution!** I cannot take responsibility if you loose anything because MacDown crashes, or reverts a document when it shouldn’t. Always backup your important documents.

### CODE REVIEW

**Comment by franklinyu** [comment]
Heroku does not support TLS from custom domain (not without [SSL Endpoint](https://devcenter.heroku.com/articles/ssl-endpoint)).

**Comment by uranusjr** [comment]
Fixed.

**Comment by franklinyu** [comment]
Synchronization works. One issue: MacDown did not update the preview after updating the source. Not even after I manually click "reload" in context menu. I need to do some dummy modification (such as add and delete a character) to trigger the re-render.

**Comment by uranusjr** [comment]
You’re right, re-rendeing is not triggered when reloading. Strange. Reloading just the preview pane wouldn’t work either because the internal HTML is not updated, but View → Render Markdown should work.

**Comment by uranusjr** [comment]
Hmm. It seems that notifications are not posted when MacDown is in background. We’re using `NSTextDidChangeNotification` to be notified for update, but we’re not getting it here. Not sure whether this is normal behaviour in OS X.

**Pull request closed without merging**
