### PR TITLE
Merge branch 'master' into touchbar-support

### PR DESCRIPTION
**Pull request by alexkaessner**
Sorry for creating a new pull request, but I wanted to help finishing #714 finally. Before starting I have to merge the `master` back into the `touchbar-support` branch.

Would be nice if @uranusjr or @franklinyu could help me merging. I don't wanna crash things 😬

### CODE REVIEW

**Comment by uranusjr** [comment]
Wow this is a lot. Reading from the title, should this be performed the other way around, i.e. merge touchbar-support into master, instead?

**Comment by alexkaessner** [comment]
@uranusjr Yeah, thats quite a lot. I want to improve just one or two things on the touch bar, than it would be ready to ship!
So I don‘t know how you want to handle it best. If you want, we can also merge it the other way round first and I create a new pull request with the few improvements from my side. What do you think? Or you merge this pull request and I continue on the the branch to merge it later back in master…

**Comment by uranusjr** [comment]
@alexkaessner The problem is there are quite some changes that are already in master, and I’m not sure whether I won’t miss anything going through the changeset. Do you have everything in the touchbar-support branch ready now? Maybe it’d be easier if I can extract the changes and apply it to master directly.

**Comment by alexkaessner** [comment]
@uranusjr Yeah sure we can do it like this. 👍 I just want to change the default touch bar layout and change the show/hide editor/preview button to match the toolbar.

**Comment by uranusjr** [comment]
I just tried to `git rebase` and it got out of hand pretty quickly 😱 Xcode XIBs are terrible.

Any chance you can manually apply the changes to the current master?

**Comment by alexkaessner** [comment]
The thing is I'm not really into the code. @brunophilipe did all the coding…I just added the icons…

[comparing master…touchbar-support here](https://github.com/MacDownApp/macdown/compare/master...touchbar-support)

**Comment by uranusjr** [comment]
Hmm, browsing through the diff the code doesn’t seem to be particularly difficult to merge. How about you open a new branch from master add all the icons in? I think I can apply the code changes from there.

**Comment by alexkaessner** [comment]
@uranusjr I actually wanted to change a few lines of code now. 😅 How about I do these few changes still on the `toolbar-support` branch and we merge it after this?

**Comment by uranusjr** [comment]
Sure, go for it.

**Pull request closed without merging**
