### PR TITLE
css: Improve PDF output

### PR DESCRIPTION
**Pull request by jckw**
These commits fix both #948 and #949 so that the PDF output is more predicable for users. This is only a tiny change, but should make a bigger change in improving user experience (particularly for non-technical users). 

I've attached a copy of the changes from the old output and the new (via the Clearness stylesheet) compared to the preview. Hopefully you can see that the updated version is much more representative of the preview. Since this editor is based on Mou, this change also makes MacDown's PDF output behave in a more similar way.

old
new
preview

There is still the issue of large headers, which is particularly noticeable in PDF outputs with dark backgrounds, e.g. Clearness Dark

split header

I believe this issue is being discussed as #359, and it may have something to do with actual PDF generation which is outside the scope of these changes (changing CSS didn't help).

Hopefully this is all good!

### CODE REVIEW

**Comment by franklinyu** [comment]
`padding` is used in GitHub style while `margin` is used in the other styles. Any reason?

**Comment by jckw** [comment]
Yep, just because the GitHub style uses `padding` instead of `margin` in the `body` style. It doesn't really make a difference, but I thought it may just be clearer for users already using a modified version of the GitHub style. 

Although, changing `padding` to `margin in the body style would be fine too!

**Comment by uranusjr** [comment]
The margins seem good to me, but why remove the color?

Also the definitions can be simplified as `margin: 2cm;`.

**Comment by jckw** [comment]
Only the `color: #000 !important` statements that force the text to be black have been removed, all the other colour stays the same.

The PDF output should reflect preview pane more accurately now and allows the text to have non-black colour.

**Comment by uranusjr** [comment]
Alright then. Maybe simply the margin syntax and we can merge!

**Comment by jckw** [comment]
Should be done!

**Pull request merged**
