### PR TITLE
Better scroll sync between editor and preview

### PR DESCRIPTION
**Pull request by adamwulf**
This pull request replaces the scrollSync with a new algorithm. The new scroll sync aligns headers and images between the editor pane and the preview pane.

As the user scrolls between two headers, the scroll % between those headers is mirrored in the preview pane. This way, large latex blocks between two headers will scroll faster in the editor than their vertically short preview. Similarly, image tags will scroll much slower in the editor than tall images in the preview pane.

This is related to #21, #287

### CODE REVIEW

**Comment by uranusjr** [comment]
Wow! I’ve been wanting to improve this for a long time, but just don’t really want to think about this difficult problem, let alone implement it. Thanks for the effot you put in. One thing I’m wondering though, does the `@import` syntax work on 10.8 (which we still currently support). I honestly have no idea.

**Comment by adamwulf** [comment]
Glad I could help! I'm loving using MacDown, and I'm glad I've found a few places where I can give back :)

As for the @import syntax, that's a very good question. not sure. i'll swap it out to <> format

**Comment by adamwulf** [comment]
I pushed up a few more commits - the @import is removed, and I've also optimized the code a bit. The original implementation added a small jitter to the scroll, but the latest comments allow it to scroll as smoothly as it did before.

**Comment by adamwulf** [comment]
Added a commit with yet another tweak: now the editor and web view will align at the middle of the window instead of aligning at the top of the window.

**Pull request merged**
