### PR TITLE
Addresses #378: Option to persistently hide preview pane

### PR DESCRIPTION
**Pull request by egirsova**
This pull request addresses issue #378.
### Additions & Changes
- Added a "Always hide preview pane" preference option to the "General Preferences" view
- `windowControllerDidLoadNib` method in MPDocument.m now first checks whether or not the preference is on or off before showing the window
  - If preference is on, then the newly created window opens with the preview pane hidden
  - If preference is off, then the newly created window opens with the preview pane shown
  - **NOTE:** This check only occurs for newly created files so that file-based persistence is maintained
- Removed a line in the `validateUserInterfaceItem` method in MPDocument.m: 
  
  ```
  it.hidden = (!self.previewVisible && self.previousSplitRatio < 0.0);
  ```
  - This line caused an issue where the "Restore Preview Pane" option in the "View" menu was hidden. This happened when a newly created file had its preview pane automatically hidden due to the new setting.
### Additional Notes

Only newly created files (via File -> New) are affected by this preference. All saved or unsaved files are unaffected because they each maintain their own persistence. In other words, this new setting essentially determines the default appearance of files (whether or not the preview pane is shown) only when they are first created. I'm not sure if this is exactly how users wanted this preference to function, but it could be a good start.

### CODE REVIEW

**Comment by uranusjr** [comment]
Sorry but I’ve been busy recently, and haven’t found time to look into the source. One question though: What happens when a file is created elsewhere (e.g. downloaded from the Internet), and opened by MacDown for the first time? It wouldn’t have a persistence, and I would expect MacDown to honour this preference in this case.

**Comment by egirsova** [comment]
@uranusjr, good question. I will look into that and report back.

**Comment by omixk** [comment]
Can you add some options to persistently hide the edit pane?

**Comment by uranusjr** [comment]
Lack of activity. I am still open for implementation, and this will continue to be tracked with #378.

**Pull request closed without merging**
