### PR TITLE
Automatically generates GitHub theme (Makefile)

### PR DESCRIPTION
**Pull request by franklinyu**
Closes #297, #952.

### CODE REVIEW

**Comment by uranusjr** [comment]
This looks good to me, but I wonder whether we want to include the generated CSS in the repository, or should make this part of the build process instead 🤔

**Comment by franklinyu** [comment]
Yes it makes sense. Where is the build script? I can include that into the build script (it's a simple `make`).

**Comment by uranusjr** [comment]
It’s part of the project file. In Xcode, click on the Project → TARGETS MacDown → Build Phases. Use the + button to add a step somewhere (probably near *Fetch Prism Resources*).

screen shot 2018-07-19 at 14 44 47

**Comment by franklinyu** [comment]
Just wondering, do I need to add `make clean` somewhere in the project file?

**Comment by uranusjr** [comment]
That’s a good question… I don’t know, maybe not? make should be able to handle file refreshing, I think. Maybe let’s not add it for now and see what happens. If this works, this works.

**Comment by uranusjr** [comment]
LGTM. Feel free to merge this if you think it’s ready.

**Pull request merged**
