### PR TITLE
Touch Bar support

### PR DESCRIPTION
**Pull request by alexkaessner**
Now it's finally time to merge the Touch Bar into master. The Touch Bar is fully functional and designed trough.

#714

### CODE REVIEW

**Comment by alexkaessner** [comment]
oh fuck no…I messed it up with the commits! Right? I was wondering why after doing the first commit today, all the latest changes came up to push 😠 

That was my commit I wanted to make…but seems like theres more broken now? **How can I/we undo this?**
bildschirmfoto 2018-02-05 um 16 53 28

**Comment by uranusjr** [comment]
Actually I think your commit is fine… Something’s wrong with Travis. Just ignore it.

**Comment by alexkaessner** [comment]
@uranusjr Strange! You are right, my commit itself is correct: 62217fe. But if you click on the title _"changed some touch bar segmented control styles"_ ([link](https://github.com/MacDownApp/macdown/pull/922/commits/62217fe4ba154499a8cdc5ade1ca77477e86282f)) of my first commit from today, you can see that all the last ~100 commits are reversed. 🤔 

If you say it's alright feel free to merge. I just want to let you know. I don't wanna break stuff. 😅

**Comment by uranusjr** [comment]
Ah, I *think* I know what’s wrong. This patch somehow rolled back some changes happened after the touchbar branch and master diverged. You can see from `.travis.yml`; we updated the image to 9.2 a while ago, but here it’s being changed back to 8.2. The `_parseHighlightsQueue` in `HGMarkdownHighlighter` is also rolled back (I think), and I guess there are many more instances like this.

I’ll take some time to try cherry-picking the changes manually tomorrow. If that doesn’t work we’re probably need to come up with something else instead.

**Comment by alexkaessner** [comment]
@uranusjr How's the status of this merge? Do you need any further help with "cherry-picking the changes manually"? Let's merge this before it gets harder with more changes.

**Comment by rmaes4** [comment]
👍 for touch bar support

**Comment by jdevalk** [comment]
Would love to see this in the app :)

**Comment by uranusjr** [comment]
My network is somehow super slow now (don’t know why), but it seems that multiple things are reverted by this (Travis config, highlighter changes, etc.) Will need to rebase them to the latest.

**Comment by franklinyu** [comment]
> multiple things are reverted by this (Travis config, highlighter changes, etc.)

And Graphviz and Bundler packages.

**Comment by uranusjr** [comment]
In Favour if #970.

**Pull request closed without merging**
