### PR TITLE
Bump CocoaPods version to latest

### LINKED ISSUE #718: Travis build failing on pod install
I see two ways to fix it.
Use a newer Xcode image with Travis:
`osx_image: xcode8.2`

Or...
Can probably be resolved by passing the `--no-repo-update` flag to `pod install`. Then of course the repo won't be updated, but *might* work as a temporary fix.

Excerpt from build log:
```
$ bundle install
$ travis_wait bundle exec pod install

Still running (1 of 20): bundle exec pod install
The command bundle exec pod install exited with 1.

Log:

Updating local specs repositories
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)
Update CocoaPods, or checkout the appropriate tag in the repo.
/Users/travis/build.sh: line 151:  3648 Terminated: 15          travis_jigger $! $timeout $cmd

The command "travis_wait bundle exec pod install" failed and exited with 1 during .

Your build has been stopped.
```

### PR DESCRIPTION
**Pull request by franklinyu**
Fixes #718.

### CODE REVIEW

**Comment by franklinyu** [comment]
Let's see whether Travis CI likes it…

**Comment by franklinyu** [comment]
Hmm, Travis CI don't complains about CocoaPods. I merged #719 to see whether it helps to build a final passing test.

**Comment by franklinyu** [comment]
WTF, no error occurs but the build timed out. I'm out of ideas.

**Comment by niklasberglund** [comment]
Seems like this is a xctool issue: https://github.com/travis-ci/travis-ci/issues/3986
`.travis.xml` states `osx_image: xcode7` so shouldn't be beta.
There's a suggested workaround to use xcodebuild instead of xctool: https://github.com/travis-ci/travis-ci/issues/3986#issuecomment-212912417

**Comment by uranusjr** [comment]
@niklasberglund @franklinyu Gosh what so now `xcodebuild` is preferred to `xctool` now? I remember when `xcodebuild` (which is used by my local publish script; see `Tools/build_for_release.py`) used to not work well on Travis, and I had to change the build script to use `xctool`. Travis’s macOS image is so annoying.

Anyway if `xcodebuild` works we should use it anyway, just to be consistent with the real release process.

**Comment by franklinyu** [comment]
I'm planning to try xctool locally, to see whether it is to blame. `xctool` is still the default on Travis CI, so I think it's better if I can make `xctool` work.

**Comment by franklinyu** [comment]
I am not familiar with `xctool`, but from

```sh
xctool -workspace MacDown.xcworkspace -scheme MacDown build test
```

I assume that it should build and test. However, in latest release, `xctool` team [stated](https://github.com/facebook/xctool/tree/0.3.1#building-xcode-7-only) that

> Support for building projects with xctool is deprecated and isn't supported in Xcode 8 and later. We suggest moving to `xcodebuild` (with `xcpretty`) for simple needs, or `xcbuild` for more involved requirements. Alternatively you can use Buck.

And [its instruction for Xcode 7](https://github.com/facebook/xctool/tree/0.3.1#xcode-7) didn't work for me (possibly because I am using Xcode 8). This changed my mind; let's switch back to `xcodebuild`. https://github.com/travis-ci/travis-ci/issues/3986#issuecomment-212912417 works on my machine, so I will try that first.

**Comment by franklinyu** [comment]
Yay! It passed!

**Comment by uranusjr** [comment]
`Podfile.lock` should be updated when `Podfile` is changed. I scanned through the xcodeproj diff and it seems to be mostly comment and hash changes, nothing significant. Rebuilding the project from scratch seems to work as well. Let’s just update it and merge this (and #719). :shipit:

**Comment by niklasberglund** [comment]
@uranusjr agreed. I kinda cheated and didn't commit it, because I'm on latest CocoaPods but the Podfile.lock was created with CocoaPods 0.39. The Podfile.lock format is slightly different - it now includes CocoaPods version and a checksum:
`PODFILE CHECKSUM: b7938bcfef3ea576dacd44005b7dbe5b4432a80f`

Should I commit it?

@franklinyu good stuff! You guys rock 😀

**Comment by uranusjr** [comment]
@niklasberglund I will do this directly on master (after merging this). I know GitHub doesn’t make pulling from other people’s forks easy, and me doing this would make things much simpler.

**Pull request merged**
