### PR TITLE
Paste image URL from clipboard when inserting image, take 2

### LINKED ISSUE #496: Auto paste image URL from clipboard when inserting image
If I insert an image using shift+cmd+i I often have the URL of the image I want to insert ready to go on my clipboard. It'd be cool if Macdown could detect that my clipboard contained an image URL and automatically insert this into the document.

I imagine people would want this enabled via a preference toggle.

### PR DESCRIPTION
**Pull request by uranusjr**
This closes #566 and fixes #496.

The implementation in #566 does not take account the original selection, so if the editor has selection before ⌘⇧I, the result would not be formatted correctly (see commit message of ceca0de). I fixed it.

Also since the link toggle uses the same logic as image (only without the `!` prefix), I also added this functionality to that action.

@getaaron Can you take a look to make sure this does work the same way as in your version?

### CODE REVIEW

**Comment by zmnv** [comment]
Will it be a realized in official version?

**Comment by uranusjr** [comment]
@zmnv Probably not unless someone takes time to rebase and test to make sure the behaviour is correct. Interested in taking a shot?

**Comment by getaaron** [comment]
@uranusjr this implementation looks great to me

**Comment by getaaron** [comment]
@uranusjr @zmnv I fixed the merge conflicts so this should be good to merge if Travis doesn’t have any objections

**Comment by uranusjr** [comment]
Let’s do this

**Pull request merged**
