### PR TITLE
Upgrade Mermaid

### LINKED ISSUE #1126: mermaid can't user axisFormat
Code like this:

```mermaid
gantt
    dateFormat YYYY-MM-DD
    title 用户体系改造工作计划
       axisFormat %m-%d
    section 后台
    数据结构  :active,a1,2019-12-12,2019-12-16
    接口相关改造  :active,a2, after a1, 3d 
    
    section APP改造
    APP改版及登录  :active,b1, 2019-12-16, 5d
    APP端相关封装 :b2, after b1, 3d
    学习培训    :b3, after b2, 7d
    二七路     :b4, after b2, 7d
    校园食安    :b5, after b2, 7d
    企业管理    :b6, after b2, 7d
    营业执照-微企 :b7, after b2, 7d
    食品许可    :b8, after b2, 7d
    APP改造完成        :crit,s,2019-12-31, 1d
    
    section 集中测试
    集中测试 :c1, after s, 9d
    
    section 上线
    预上线 :d1, 2020-01-10,7d

```

In typora is Ok.
image

### LINKED ISSUE #1138: Graphviz's filled and color attributes doesn't work
Like

`digraph {
node [style=filled,color=white];
a -> b
}`

The result is:
image

On viz-js.com , it seems :

image

I know why!.
The mermaid we use is older version, it's css file 'mermaid.forest.css'  override the node's style.

So, If we upgrade the mermeiad, we do not need the mermaid.forest.css file. So it is ok.

Like this:
image

### PR DESCRIPTION
**Pull request by Gowa2017**
Upgrade Mermaid.js for better Gantt chart.

Fixes #1126. Fixes #1138.

---

升级一下 mermaid 更好的支持 甘特图。

### CODE REVIEW

**Comment by FranklinYu** [comment]
Which version of Mermaid is this? It’s unclear from the file.

---

这是哪个版本的 Mermaid？文件中看不出来。

**Comment by Gowa2017** [comment]
我晚点看一下 都用中文 为什么项目都出英文的

**Comment by Gowa2017** [comment]
> Which version of Mermaid is this? It’s unclear from the file.
> 
> 这是哪个版本的 Mermaid？文件中看不出来。

用的是8.4.3 的 https://unpkg.com/mermaid@8.4.3/dist/mermaid.min.js

**Comment by FranklinYu** [comment]
Most users don’t speak Chinese.

---

大部分用户不说中文。

**Review by FranklinYu — APPROVED** [review]

**Comment by legoming** [comment]
@FranklinYu will you release a version to include this update recently?

**Comment by FranklinYu** [comment]
@legoming I’m working on next release in testing channel, but I cannot give any guarantee.

**Comment by besi** [comment]
Hello there. I am using The current test version of MacDown `0.8.0d71 (1079)`.
I'm trying to include a [flowchart diagram](https://mermaid.js.org/syntax/flowchart.html) in Macdown which does not work unfortunately:

Screenshot 2025-02-18 at 01 54 44

First I thought that this might be a version issue but it seems that flow charts are there since the very beginning in 2014:
https://github.com/mermaid-js/mermaid/releases/tag/0.1.0

**Comment by besi** [comment]
I changed my comment into a new issue: See #1343

**Pull request merged**
