### PR TITLE
Check for .md file existence on link click.

### LINKED ISSUE #1085: Link to *.md file if no extension provided
Hi @uranusjr 

I've just discovered MacDown and I find it fantastic to manage the wikis of my projects. However, in projects hosted on Gitlab, if one clicks on a link without any extension, the browser redirects to the related .md file.

MacDown behaves differently and just asks for the user to activate this option: 'Automatically create files for link targets'. If activated, a new empty file is created and may overwrite the previous one as by default, the save panel will add the .md etension.

I've forked and implemented a solution for that issue. Feel free to merge it if you think it's useful for your app.

### PR DESCRIPTION
**Pull request by CDOApps**
Closes #1085

### CODE REVIEW

**Comment by FranklinYu** [comment]
I like the idea, but in this case we can be more aggressive. For bare path without file extension like `[this][file-name]`, I think we can simply create `file-name.md`. This is not necessarily `.md`; if I recall correctly user can specify a preferred extension.

**Comment by CDOApps** [comment]
> I like the idea, but in this case we can be more aggressive. For bare path without file extension like `[this][file-name]`, I think we can simply create `file-name.md`.

Tell me if I'm wrong, isn't what MacDown's doing if the file doesn't exist?

> This is not necessarily `.md`; if I recall correctly user can specify a preferred extension.

I didn't see where to define a preferred extension but it sounds better than using hard coded `.md` for extension. Actually, I based my solution on the `prepareSavePanel:` which fills the path with `.md` if the file name is not using this for extension.

**Comment by FranklinYu** [comment]
@CDOApps Oh then maybe MacDown is already doing that. In that case we can merge this as-is. Let me check this week when I get back to my Mac… Currently using Windows.

**Comment by uranusjr** [comment]
Maybe we can check for more stuffs (e.g. check for UTI instead of extension, but this good enough as-is.

**Pull request merged**
