### PR TITLE
Updated app icon to match the new Big Sur style

### PR DESCRIPTION
**Pull request by alexkaessner**
As voted by issue #1208, this is a new app icon version for the all new Big Sur design.

### CODE REVIEW

**Comment by FranklinYu** [comment]
I see that 32x32 is removed. Was that by accident?

**Comment by alexkaessner** [comment]
@FranklinYu Looks indeed like it on GitHub, but the 32px and 32px@2x are still in the repo. They are just smaller in file size. When you open the diff you can see they are still there: https://github.com/MacDownApp/macdown/pull/1221/commits/3cfb5fc984534486500413a03806ce85da831ff0#diff-43dcfaa0d11ed7af25241565c538adc7045bf05e1d73624acc28068cb89cbdf1

**Review by FranklinYu — APPROVED** [review]
LGTM

**Comment by FranklinYu** [comment]
Sorry, I guess I was confused by the web interface, and thought the red highlight means removal of files. Thank you for the contribution!

**Comment by alexkaessner** [comment]
@FranklinYu No worries, I also thought that at first after you’ve pointed that out. I had to double check this as well. Thanks for the merge!! 💙

**Pull request merged**
