### PR TITLE
[WIP] Open Quickly

### PR DESCRIPTION
**Pull request by orta**
OK, this is a WIP PR, I've got a while to go, but getting feedback early is important - especially when it involves design on someone else project. I initially started this because I was procrastinating on a book, now I'm ready to devote some real effort to the project.

So, right now it looks like:

screen shot 2015-09-07 at 12 16 25 am

but I took some time to mock up in Sketch what I want the end results of my changes to look like.

macdown2

If you just do "Open Quickly" it would show your markdown files in order of most recently changed, you can press up/down (or double click) to select a document, it would use use the NSDocument open URL. so if the window already existed it would bring that to front.

If you type anything else it would go into the default search query bar, filtering the list down by title. Again, you can press up/down to switch between files. I've based it on TextMate's Open Quickly, which feels closest to what I want.

So, does this feel like a direction you're happy with? ( Don't review the code yet, it's far from ready ;) )
### My TODO:
- [ ] Only allows open quickly when you have a file that is saved in a folder
- [x] Shows recent docs by default
- [ ] Goes back to recent docs when you have no query
- [ ] Up/Down moves between selected items
- [x] Mouse double click support
- [ ] Escape hides the window
- [x] Searches within current folder
- [ ] Filters irrelevant results
- [ ] Ensure that it works on 10.8

### CODE REVIEW

**Comment by uranusjr** [comment]
This looks awesome. I can do without the close button though; it should be intuitive enough to use Esc to close the popup. (Not that I would object if you think it should be there.)

I think this can be used to open files with path, too. If you type `./` or `../` inside the search box, the bottom would list files and directories inside the current directory. You can then go on typing, or uses the arrow and enter keys to get to the file you want. This is (IMO) a much more elegant way to integrate file navigation into MacDown than the much requested tree view (discussed in #141).

The two usages don’t conflict though, so the file system navigation thing can come later. I’ll fetch the changes and try it out later this week. I’m really excited about this.

**Comment by orta** [comment]
Great! 

A lot of the core structure is in place ( finding documents, string matching for the query ) - it's going to be polish from here on in. I think I prefer it with the close button, it makes it feel like a window rather than a popup.

macdowngif

**Comment by uranusjr** [comment]
> I think I prefer it with the close button, it makes it feel like a window rather than a popup.

Good point. :)

BTW do you have an idea why the Travis checks error? It seems that compilation fails because `NSSearchField` cannot be found. But it should be, being available since 10.3 (at least that’s what [the documentation](https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSSearchField_Class/index.html) says).

**Comment by orta** [comment]
Do you have any opinions on migrating to Xcode 7? I can do the travis stuff once I've got it working. Would be nice to use [lightweight generics](http://www.miqu.me/blog/2015/06/09/adopting-objectivec-generics/).

**Comment by uranusjr** [comment]
I just migrated the project file to Xcode 7, and it seems that there are some build issues with the new `__nullable` decorator (is this the correct term?) and some Makefile project settings, and the builds are currently failing.

Let’s just move to Xcode 7 and worry about Travis (and other stuffs) later, as long as the final product works (with support to 10.8+). The master is now Xcode 7-ready, and you might want to pull it.

**Comment by orta** [comment]
:+1:  awesome

**Comment by getaaron** [comment]
@orta Are you planning to keep working on this? If yes, any interest in pairing on it?

**Comment by orta** [comment]
Nope, it should probably be closed - you're welcome to wrap it up ( or turn it into a MacDown plugin )

**Pull request closed without merging**
