### PR TITLE
x-macdown URL scheme implementation

### PR DESCRIPTION
**Pull request by mixio**
Open a file from a browser with url of the form "x-macdown://open?url=file:///path/to/a/file&line=123&column=45"

FIXME: Could not figure out how to place the insertion point at a given line and column.

### CODE REVIEW

**Comment by uranusjr** [comment]
The implementation looks good to me. Could you add some line breaks so the lines don’t get too long? We generally try to keep lines under 80 characters long (not a hard rule, but please try). Thanks so much!

**Comment by mixio** [comment]
Added some line breaks to try to keep lines under 80 characters long. Best regards.

**Comment by uranusjr** [comment]
There’s no built-in way to do this AFAIK, so you probably need to parse the URL yourself and tap into [NSTextView](https://developer.apple.com/documentation/appkit/nstextview) API to move the cursor yourself.

I’ll merge this as-is because everything works already. We can add the auto-jump feature separately.

**Review by uranusjr — APPROVED** [review]

**Comment by roycetech** [comment]
I was so glad to learn that MacDown supports custom URL scheme. I wanted to be able to open a Markdown file from a link in another Markdown, but I couldn't get it to work. Is this feature still working? I'm on an M1 Pro.

**Pull request merged**
