### PR TITLE
Realign Tiglou mermaid - graphviz branch

### PR DESCRIPTION
**Pull request by loopingz**
And add LICENCE and Credits as requested

Closes #625.

### CODE REVIEW

**Comment by uranusjr** [comment]
Since there’s no response from @tinglou I’ll just go ahead and merge this. Thanks everyone for sticking around! Testing release coming up.

**Comment by legoming** [comment]
is there any test version with mermaid support?

**Comment by uranusjr** [comment]
@legoming I released one yesterday. You should get it if you turned on auto updates.

**Comment by legoming** [comment]
Update detected, thanks a lot.

**Comment by legoming** [comment]
There're two issues during my testing:
1. flow chart repeated twice
2. app frozen easily during edit

**Comment by franklinyu** [comment]
@legoming Please provide [Minimal Working Example](https://en.wikipedia.org/wiki/Minimal_Working_Example) for us to reproduce the two issues.

**Comment by loopingz** [comment]
I reproduce the repeat, I will check on my side

**Comment by loopingz** [comment]
I have the fix ready will push another PR with the issue

**Comment by loopingz** [comment]
I am able to reproduce with the Chinese caracters, it might be a limitation from Mermaid but i don't think there is much we can do.

**Comment by legoming** [comment]
Got it. Thanks.

**Comment by tempelmann** [comment]
Huh, I just installed the latest update (0.7.2d137, with Copyright 2014–2016), and it doesn't seem to support mermaid - and the Help does not mention it, either. What am I missing here?

**Comment by uranusjr** [comment]
I just made a new release today and might have messed something up. Will investigate.

**Comment by inevity** [comment]
Any progress? Have build the master ,also no mermaid or graphviz in preferences.

**Pull request merged**
